repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext', 'md']
      - id: mixed-line-ending
        args: ['--fix', 'no']
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.10.1
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  #     - id: isort
  #       name: isort (cython)
  #       types: [cython]
  #     - id: isort
  #       name: isort (pyi)
  #       types: [pyi]
  # - repo: https://github.com/PyCQA/pylint
  #   rev: v2.14.4
  #   hooks:
  #     - id: pylint
